language: elixir

jobs:
  include:
    - elixir: 1.10.2
      otp_release: 21.0
    - elixir: 1.9.4
      otp_release: 20.3
    - elixir: 1.8.2
      otp_release: 20.3
sudo: false
before_script:
  - mix deps.get
script:
  - mix compile
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
