language: elixir
elixir:
  - 1.7.1
  - 1.7.0
  - 1.6.6
  - 1.6.5
otp_release:
  - 21.0
  - 20.3
  - 20.1
  - 20.0
sudo: false
before_script:
  - mix deps.get
script:
  - mix compile
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
