language: elixir
elixir: 1.6.3
otp_release:
  - 20.2.2
sudo: false
before_script:
  - mix deps.get
script:
  - mix compile
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
